spring:
  devtools:
    restart:
      enabled: true
      additional-paths: src/main/java
      exclude: WEB-INF/**

  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/fwzd?useUnicode=true&characterEncoding=UTF-8&serverTimezone=Asia/Shanghai
    username: root
    #☁密码:114514,本地密码:Simon@123
    password: Simon@123

  servlet:
    multipart:
      max-file-size: 100MB
      max-request-size: 100MB
      enabled: true
      location:
      resolve-lazily: false

server:
  port: 11455


mybatis:
  configuration:
    map-underscore-to-camel-case: true
